logging:
  level:
    org.springframework: ERROR
    com.adri.economy: DEBUG
spring:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    datasource:
      platform: h2
    h2:
      console:
        enabled: true
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
