logging:
  level:
    org.springframework: ERROR
    com.adri.economy: DEBUG
spring:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    datasource:
      platform: h2
    h2:
      console:
        enabled: true
    jpa:
      show-sql: false
      properties:
        hibernate:
          format_sql: false
kafka:
  bootstrapAddress: rocket-01.srvs.cloudkafka.com:9094, rocket-02.srvs.cloudkafka.com:9094, rocket-03.srvs.cloudkafka.com:9094
  username: v5bn5q8c
  password: jw3-bNa5Ybw8KNc35RereJY5NsHKVZZY
  topic:
    operation: v5bn5q8c-dev-operation-topic
  group:
    balance: balance-consumer-dev
